---
title: "GeneSet_Expansion"
output: html_document
---

```{r setup, include=FALSE}
# Source modified utility functions from limma and sva package
source("~/TWAS/code/utilityFunctions/Parallel_vbsrBootstrap.R")
library(parallel)
library(doParallel)
library(spike)
library(reshape2)
library(biomaRt)
library(data.table)

source('~/TWAS/utilityFunctions/parallelDuplicateCorrelation.R')
source('~/TWAS/utilityFunctions/irwsva.build.R')
source('~/TWAS/utilityFunctions/f.pvalue.R')
library(biomaRt)

knitr::opts_chunk$set(
  echo=FALSE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  cache = TRUE)
```

## Load in Regions and build genesets from BioMart
```{r Load}
Regions <- read.table( file='../Reference_Files/Gene_Hit_Regions.bed', header=F, sep='\t')

row.names(Regions) <- Regions$V4

Regions[ c("TREM2", "CD2AP", "MTCH2", "EED", "APOC1","CEACAM19","CLPTM1"), ]$V2 <- Regions[ c("TREM2", "CD2AP", "MTCH2", "EED", "APOC1","CEACAM19","CLPTM1"), ]$V2+500000
Regions[ c("TREM2", "CD2AP", "MTCH2", "EED", "APOC1","CEACAM19","CLPTM1"), ]$V3<-Regions[ c("TREM2", "CD2AP", "MTCH2", "EED", "APOC1","CEACAM19","CLPTM1"), ]$V3-500000

mart <- useMart("ensembl", host="grch37.ensembl.org", dataset = "hsapiens_gene_ensembl")
#mart <- useMart(biomart = "ENSEMBL_MART_ENSEMBL", host = "jul2019.archive.ensembl.org", dataset = "hsapiens_gene_ensembl")
#mart <- useMart(biomart = "ENSEMBL_MART_ENSEMBL", dataset = "hsapiens_gene_ensembl")

#row.names(Regions) <- Regions$V4

Candidates <- list()
for( name in as.character(Regions$V4) ){
  
  filterlist <- paste0( Regions[ name, ]$V1, ':', Regions[ name, ]$V2, ':', Regions[ name, ]$V3 )

  ## Query biomart
  eval(parse(text= paste0( 'Candidates$', name, ' <- getBM(attributes = c(\'ensembl_gene_id\', 
                                        \'hgnc_symbol\', 
                                        \'chromosome_name\', 
                                        \'start_position\', 
                                        \'end_position\'),
                        filters = c(\'chromosomal_region\'), 
                        values = filterlist,
                        mart = mart)'
  )))
}

for( name in as.character(Regions$V4) ){
  eval(parse(text= paste0( 'Candidates$', name, ' <- Candidates$', name, '[ (Candidates$', name, '$hgnc_symbol == \'\') == F, ]' )))
}
```

## Expand Target List
```{r Expand, echo=FALSE}

reticulate::use_python("/usr/bin/python", required = TRUE)
synapseclient <- reticulate::import("synapseclient")
syn_temp <- synapseclient$Synapse()
syn_temp$login()

#SynIDs of expression data to pull from
ExpressionDS <- c('syn21292041','syn21285564','syn21285564','syn21285564','syn21285564','syn21291908')
names( ExpressionDS ) <- c( 'DLPFC', 'FP', 'IFG', 'PHG', 'STG', 'TCX')

#Study ID Translator
Study <- c( 'RosMap', 'Mayo', 'MSBB', 'MSBB', 'MSBB', 'MSBB')
names(Study) <- c('DLPFC', 'TCX', 'FP', 'IFG', 'PHG', 'STG')

Syn <- list('DLPFC', 'TCX', 'FP', 'IFG', 'PHG', 'STG')

Partials <- list()

library(parallel)
library(doParallel)
#detach("package:doParallel", unload=TRUE)
#detach("package:parallel", unload=TRUE)
cores <- detectCores()-2 
cl <- makePSOCKcluster(cores)
registerDoParallel(cl)

mark <- Sys.time()
for( name in as.character(Regions$V4) ){
 #for( Tissue in names(ExpressionDS)){
 for( Tissue in names(ExpressionDS) ){
  message(paste0("Working on: ", Tissue))
  #Tissue<-'DLPFC'

  #Load expression for tissue
  exp <- read.table(syn_temp$get(as.character(ExpressionDS[Tissue]))$path, header =T, sep ='\t', row.names=1)
  colnames( exp ) <- gsub( "X", "", colnames( exp ) )
  #Seperate exp by tissue
  if( Tissue == 'DLPFC'){
  }else{
    if( Tissue == 'TCX' | Tissue == 'CBE' ){
      if( Tissue == 'CBE' ){
        slec <- 'CER'
      }else{ slec <- 'TCX' }
      colnames( exp ) <- gsub( "TC", "TCX", colnames( exp ) )
      exp <- exp[ , grepl( slec, colnames(exp)) ]
    }else{
      if( Tissue %in% c('FP', 'IFG', 'PHG', 'STG') ){
        Meta <- read.table( syn_temp$get('syn21285520')$path, header =T, sep ='\t', row.names=1 )
        exp <- exp[ colnames(exp) %in% row.names(Meta[grepl( Tissue, Meta$Tissue.Diagnosis),])]
      }else{
        stop(paste0("ERROR: SOURCE=Config.yaml Issue=Tissue: ", Tissue," is improper must be one of: CBE, DLPFC, FP, IFG, PHG, STG, TCX"))
      }
    }
  }
  
  #Impute svalues for given gene-patient NA values
  exp <- exp[rowSums(is.na(exp))<ncol(exp), ]
  
  foo <- bcv::impute.svd( t(exp) )
  Exp <- foo$x
  row.names(Exp) <- row.names(t(exp)) 
  colnames(Exp) <- colnames(t(exp)) 
  
  #Prep for partial correlation detection
  Final <- data.frame()
  
  source("~/TWAS/code/utilityFunctions/Parallel_vbsrBootstrap.R")
  #Run Partial correlations for each gene
  
  RUNNe <- function( i=i, x=Exp ){ 
    library(parallel)
    library(doParallel)
    source("~/TWAS/code/utilityFunctions/Parallel_vbsrBootstrap.R")
    OBS <- i
    y <- as.matrix(x[,OBS]) 
    colnames(y) <- i
    X <- x[,(colnames(x) %in% OBS) == F ]
    att <- pvbsrBootstrap( y=y, x=X, nsamp=100, cores=1 )
    names( att ) <- gsub( "intercept", OBS, names(att) )
    att <- c( 'SeedGene' = OBS, att[ colnames(x) ]) 
    return( att[c( 'SeedGene', colnames(x) )] )
    #return(eval(parse( text = paste( c( OBS,att[colnames(x)]), sep='\t') )))
  }
  
  LIST <- eval( parse( text= paste0( 'Candidates$',name,'$ensembl_gene_id' )))  
  LIST  <- LIST[ (LIST %in% colnames(Exp) ) ==T ]
  
  mark <- Sys.time()
    foo <- t( parApply(cl, as.matrix( LIST[1:length(LIST)] ), 1, RUNNe, Exp) )
  message( paste0( Sys.time()-mark )) 
  
  eval(parse(text=paste0( 'Partials$', name, '$', Tissue, '<- foo' )))
  
  message(paste0( "Finished Tissue: ", Tissue, ' For Gene: ', name ))
 }
  message(paste0( "Completed All Tissues Finished Seed Gene: ", name ))
}
mark-Sys.time()
#sink<-Partials

```

```{r Selected, echo=FALSE}
#Average the partial correlation statistics across the data  frames

GENEs <- NULL
for( tissue in names(Partials$TREM2) ){
  GENEs <- eval(parse( text=paste0('c(GENEs, colnames(Partials$TREM2$',tissue,'))') ))
  GENEs <- GENEs[ !duplicated(GENEs) ]
}

GENEs <- GENEs[ GENEs != 'SeedGene' ]
ensembl <- useMart("ENSEMBL_MART_ENSEMBL", host = 'ensembl.org')
ensembl <- useDataset('hsapiens_gene_ensembl', mart = ensembl)

Top50_Cor <- function( ENSG, Targets, Tissues, Part, ensembl ){
  #'@ENSG the target gene ID to collect partials on eg. 'ENSG00000095970'
  #'@Targets a vector of ENSG names to scan eg. GENEs
  #'@Tissues charater vector of tissues to scan eg. c( "FP", "TCX", "DLPFC", "IFG", "PHG", "STG"  )
  #'@Part a partial correlation list  eg. Partials$TREM2
  #'@ensembl ensembl object eg. ensembl
  
  Examine <- matrix( NA, length(Targets), length(Tissues)+1 )
  Examine <- apply(Examine, 2, as.numeric)
  row.names(Examine) <- Targets
  colnames(Examine) <- c( Tissues, "Avg" )
  
  for( Tis in Tissues ){
    eval(parse( text= paste0( 'Examine[ colnames(Part$\'', Tis,'\')[ colnames(Part$\'', Tis,'\') !=\'SeedGene\' ],\'', Tis, '\' ]  <- as.numeric( Part$\'', Tis, '\'[ Part$\'', Tis,'\'[ ,\'SeedGene\'] == \'', ENSG, '\' , colnames(Part$\'', Tis,'\') != \'SeedGene\' ])' ) ))
  }
    
  Examine[, 'Avg' ] <- apply( Examine[ , 1:(dim(Examine)[2]-1) ], 1, mean )
  Examine <- Examine[ order(-Examine[,'Avg']), ] 
    
  #message(paste0("1"))  
  #ensembl <- useMart("ENSEMBL_MART_ENSEMBL", host = 'ensembl.org')
  #message(paste0("2"))
  #ensembl <- useDataset('hsapiens_gene_ensembl', mart = ensembl)
  #message(paste0("3"))
  gene_ids <- row.names( Examine )[1:50] 

  attrs <- c("ensembl_gene_id", "hgnc_symbol")
  Trans <- getBM(filters = 'ensembl_gene_id',
                            attributes = attrs,
                            values = gene_ids,
                            mart = ensembl )
    
  return( Trans$hgnc_symbol[ Trans$hgnc_symbol != "" ] )
}

Top50 <- list()
Top50$Trem <- Top50_Cor( 'ENSG00000095970', GENEs, c( "FP", "TCX", "DLPFC", "IFG", "PHG", "STG"  ), Partials$TREM2, ensembl )
Top50$CD2AP <- Top50_Cor( 'ENSG00000198087', GENEs, c( "FP", "TCX", "DLPFC", "IFG", "PHG", "STG"  ), Partials$CD2AP, ensembl )
Top50$MTCH2 <- Top50_Cor( 'ENSG00000109919', GENEs, c( "FP", "TCX", "DLPFC", "IFG", "PHG", "STG"  ), Partials$MTCH2, ensembl )
Top50$EED <- Top50_Cor( 'ENSG00000074266', GENEs, c( "FP", "TCX", "DLPFC", "IFG", "PHG", "STG"  ), Partials$EED, ensembl )
Top50$KNOP1 <- Top50_Cor( 'ENSG00000103550', GENEs, c( "FP", "TCX", "DLPFC", "IFG", "PHG", "STG"  ), Partials$KNOP1, ensembl )
Top50$APOC1 <- Top50_Cor( 'ENSG00000130208', GENEs, c( "FP", "TCX", "DLPFC", "IFG", "PHG", "STG"  ), Partials$APOC1, ensembl )
Top50$CEACAM19 <- Top50_Cor( 'ENSG00000186567', GENEs, c( "FP", "TCX", "DLPFC", "IFG", "PHG", "STG"  ), Partials$CEACAM19 , ensembl )
Top50$CLPTM1 <- Top50_Cor( 'ENSG00000104853', GENEs, c( "FP", "TCX", "DLPFC", "IFG", "PHG", "STG"  ), Partials$CLPTM1, ensembl )
```

```{r SIF_Load, echo=FALSE}
reticulate::use_python("/usr/bin/python", required = TRUE)
synapseclient <- reticulate::import("synapseclient")
syn_temp <- synapseclient$Synapse()
syn_temp$login( )

SIFs <- c('syn21914055')
names(SIFs) <- c('All')

#Load and Add names: SIFs
boot <- function( i ){
  foo <- read.table( file=syn_temp$get( SIFs[i] )$path , header = F, sep='\t' )
  foo$Pathway <- as.character( i ) 
  return(foo)
}

Loader <- function( SIFs){
  #'@SIFs An object that has SynID values and named for the database
  ##  Each Syn ID is a SIF format file 
  
  total <- list()
  Trial <- for( i in names(SIFs) ){
    temp <- boot( i )
    #eval(parse(text=paste0( 'total$', as.character(NAMES[i]), ' <- temp' )))
    total[[i]] <- temp
  }
  
  Total <- do.call(rbind, total)
  Total <- Total[ , c("V1", "V3", "V2", "Pathway") ]
  colnames(Total) <- c("from", "to", "interaction", "pathway")
  
  #Caluclate how many times this intereactcion was found in all databases:
  Total$Occurance <- paste0( Total$from, '-', Total$to, ':', Total$interaction )
  foo <- paste0( Total$from, '-', Total$to, ':', Total$interaction )
  TabFoo <- table(foo)
  Total$Occurance <-  as.numeric( TabFoo[ Total$Occurance ] )
  
  Genes <- c( as.character(Total$from), as.character(Total$to) )
  Genes <- Genes[ !duplicated(Genes) ]
  Genes <- as.data.frame( Genes )
  
  #Make the pathway column into a list object
  #library(dplyr)
  #library(reshape)
  
  
  Total$UniqCol <- paste0( as.character(Total$from),':', as.character(Total$to),'-', as.character(Total$interaction) )
  dt <- data.table(Total[, c('UniqCol','pathway')])
  DT <- dt[,lapply(.SD, function(col) paste(col, collapse=", ")), by=.(UniqCol)]
  
  sinl<-DT
  
  foo <- as.data.frame( DT )
  poo <- as.list( strsplit(as.character(foo$pathway),',') )
  names(poo) <- foo$UniqCol
  
  totals <- Total[ !duplicated(Total$UniqCol), ]
  pathways <- poo
  
  table(names(pathways) == as.character(totals$UniqCol))
  table( as.character(totals$UniqCol) == names(pathways) )
  
  totals$PATH <- pathways
  totals$PATH <- lapply( totals$PATH,
                 function(x) gsub(" ","", x)
               )
  
  Total <- totals[,c("from", "to", "interaction", "Occurance", "UniqCol", "PATH")]
  colnames(Total) <- c("from", "to", "interaction", "Occurance", "UniqCol", "pathway")
  return( Total )
}

Total <- Loader(SIFs)
Total$from <- as.character(Total$from)
Total$to <- as.character(Total$to)
Total$UniqCol <- as.character(Total$UniqCol)
dim(Total)
table(table( Total$UniqCol ))
#Filter out the :CHEBI
Total <- Total[ (grepl( ':CHEBI', Total$UniqCol) == F) , ]

#Remove Repeat interactions?
Total$Partners <- paste0(Total$from, ":", Total$to )
Total <- Total[ !duplicated(Total$Partners), ]

```

```{r SIF_Expand, echo=FALSE}
Expand_gt1 <- list()
Expand_gt2 <- list()

#Convert Brain Expressed to Gene names
ensembl = useEnsembl(biomart = "ensembl", dataset = "hsapiens_gene_ensembl" )
GENEsyb <- getBM(attributes = c('hgnc_symbol'), 
      filters = 'ensembl_gene_id', 
      values = GENEs, 
      mart = ensembl)

for( nam in names(Top50) ){
  genes <- eval(parse(text=paste0( 'Top50$', nam )))
  Exp <- c( Total[ Total$from %in% genes | Total$to %in% genes, ]$from, 
            Total[ Total$from %in% genes | Total$to %in% genes, ]$to
          )
  
  #Filt out molecule intereactions and split into conservative and non conservative
  gt1 <- names( table(Exp)[ table(Exp) > 1 ] )
  gt1 <- gt1[ grepl( 'CHEBI:', gt1) == F ]
  gt2 <- names( table(Exp)[ table(Exp) > 2 ] )
  gt2 <- gt2[ grepl( 'CHEBI:', gt2) == F ]
  
  #Filt for brain expressed Genese
  eval(parse(text=paste0( 'Expand_gt1$', nam, ' = gt1[ gt1 %in% GENEsyb[,\'hgnc_symbol\'] ] ' )))
  eval(parse(text=paste0( 'Expand_gt2$', nam, ' = gt2[ gt2 %in% GENEsyb[,\'hgnc_symbol\'] ] ' )))
}

library( clusterProfiler )
library(enrichplot)
library(enrichR)
library(org.Hs.eg.db)

parentId = 'syn18936948';
activityName = 'Gene Set Enrichment';
activityDescription = 'Figure 4 & Supplement: gene set enrichment of genes implicated in TWAS regions';
thisFileName <- 'GeneSet_Expansion.Rmd'
# Github link
thisRepo <- githubr::getRepo(repository = "jgockley62/TWAS", ref="branch", refName='master')
thisFile <- githubr::getPermlink(repository = thisRepo, repositoryPath=paste0('code/',thisFileName))

CODE <- syn_temp$store(synapseclient$Folder(name = "Gene Set Enrichment Plots", parentId = parentId))

for( name in names(Expand_gt2)){
  eval(parse(text=paste0('set <- Expand_gt2$', name )))
  ego <- enrichGO(gene            = set,
                    universe      = GENEsyb[,'hgnc_symbol'],
                    OrgDb         = org.Hs.eg.db,
                    keyType      = 'SYMBOL',
                    ont           = "ALL",
                    pAdjustMethod = "BH",
                    pvalueCutoff  = 0.01,
                    qvalueCutoff  = 0.05
                  )
  
  clusterProfiler::dotplot(ego, x = "GeneRatio", showCategory=30)
  cnetplot(ego, foldChange=NULL)
  
  
  Dot <- clusterProfiler::dotplot(ego, x = "GeneRatio", showCategory=30)
  Net <- cnetplot(ego, foldChange=NULL)
  
  pdf(file = paste0("EnrichmentDotPlot_", name, "_GeneSetSize_", length(set),"_gt2.pdf"), width = 14, height = 7)
    print( clusterProfiler::dotplot(ego, x = "GeneRatio", showCategory=30) )
  dev.off()
  ENRICH_OBJ <-  syn_temp$store( synapseclient$File( path=paste0("EnrichmentDotPlot_", name, "_GeneSetSize_", length(set),"_gt2.pdf"), name = paste0("EnrichmentDotPlot_", name, "_GeneSetSize_", length(set),"_Gene apperars gt 2 times"), parentId=CODE$properties$id ), activityName = activityName, executed = thisFile, activityDescription = activityDescription)
  
  pdf(file = paste0("EnrichmentNetPlot_", name, "_GeneSetSize_", length(set),"_gt2.pdf"), width = 14, height = 7)
    print( clusterProfiler::dotplot(ego, x = "GeneRatio", showCategory=30) )
  dev.off()
  ENRICH_OBJ <-  syn_temp$store( synapseclient$File( path=paste0("EnrichmentNetPlot_", name, "_GeneSetSize_", length(set),"_gt2.pdf"), name = paste0("EnrichmentNetPlot_", name, "_GeneSetSize_", length(set),"_Gene apperars gt 2 times"), parentId=CODE$properties$id ), activityName = activityName, executed = thisFile, activityDescription = activityDescription)
}

for( name in names(Expand_gt1)){
  eval(parse(text=paste0('set <- Expand_gt1$', name )))
  ego <- enrichGO(gene            = set,
                    universe      = GENEsyb[,'hgnc_symbol'],
                    OrgDb         = org.Hs.eg.db,
                    keyType      = 'SYMBOL',
                    ont           = "ALL",
                    pAdjustMethod = "BH",
                    pvalueCutoff  = 0.01,
                    qvalueCutoff  = 0.05
                  )
  
  clusterProfiler::dotplot(ego, x = "GeneRatio", showCategory=30)
  cnetplot(ego, foldChange=NULL)
  
  
  Dot <- clusterProfiler::dotplot(ego, x = "GeneRatio", showCategory=30)
  Net <- cnetplot(ego, foldChange=NULL)
  
  pdf(file = paste0("EnrichmentDotPlot_", name, "_GeneSetSize_", length(set),"_gt1.pdf"), width = 14, height = 7)
    print( clusterProfiler::dotplot(ego, x = "GeneRatio", showCategory=30) )
  dev.off()
  ENRICH_OBJ <-  syn_temp$store( synapseclient$File( path=paste0("EnrichmentDotPlot_", name, "_GeneSetSize_", length(set),"_gt1.pdf"), name = paste0("EnrichmentDotPlot_", name, "_GeneSetSize_", length(set),"_Gene apperars gt 1 times"), parentId=CODE$properties$id ), activityName = activityName, executed = thisFile, activityDescription = activityDescription)
  
  pdf(file = paste0("EnrichmentNetPlot_", name, "_GeneSetSize_", length(set),"_gt1.pdf"), width = 14, height = 7)
    print( clusterProfiler::dotplot(ego, x = "GeneRatio", showCategory=30) )
  dev.off()
  ENRICH_OBJ <-  syn_temp$store( synapseclient$File( path=paste0("EnrichmentNetPlot_", name, "_GeneSetSize_", length(set),"_gt1.pdf"), name = paste0("EnrichmentNetPlot_", name, "_GeneSetSize_", length(set),"_Gene apperars gt 1 times"), parentId=CODE$properties$id ), activityName = activityName, executed = thisFile, activityDescription = activityDescription)
  
  
}



```





##### Deprecated:
```{r SDcutOff }
library(doParallel)
library(parallel)

#Core Correlation:
Narrow <- list()

#Filter out un-named genes:
for( Gene in names(Candidates)){
  eval(parse(text=paste0( 'Candidates$', Gene, ' <- Candidates$', Gene, '[ (Candidates$', Gene, '$hgnc_symbol == \'\' )==F, ]' )))
}


Trans  <- c("ENSG00000095970", "ENSG00000198087", "ENSG00000109919", "ENSG00000074266", "ENSG00000130208", "ENSG00000103550", "ENSG00000186567", "ENSG00000104853")
names(Trans) <- c("TREM2", "CD2AP", "MTCH2", "EED", "APOC1", 'KNOP1', "CEACAM19", "CLPTM1")


#Find Partials to Nominated Target gene:
##Filter out un-named genes (Wont work in Enrichr):
for( Gene in names(Candidates) ){
  for( Tissue in names(Study) ){
    eval(parse(text=paste0( 'Candidates$', Gene, '$', Tissue, ' <- NA')))
    eval(parse(text=paste0( 'row.names( Candidates$', Gene, ') <- Candidates$', Gene, '$ensembl_gene_id')))
    
    for( G in eval(parse(text=paste0( 'Candidates$', Gene, '$ensembl_gene_id' ))) ){
      #[\'', G ,'\' ]
      
      eval(parse(text=paste0( 'Temp <- Partials$', Gene , '$', Tissue, '[ Partials$', Gene , '$', Tissue, '[,\'SeedGene\'] == \'', Trans[Gene],'\',]' )))
      if( (G %in% names( Temp ))==TRUE){
        eval(parse(text=paste0( 'Candidates$', Gene, '[ \'',G,'\',\'', Tissue, '\'] <- as.numeric(Temp[\'',G,'\'])' )))
      }else{}
    
    }
  }
}

#Average Partial Correlation to Nominated Target accross the 6 tissues
for( Gene in names(Candidates) ){
  eval(parse(text=paste0( 'Candidates$', Gene,'$MEAN <- apply( Candidates$', Gene,'[,c(\'DLPFC\', \'TCX\', \'FP\', \'IFG\', \'PHG\', \'STG\')], 1, mean)')))
}

for( Gene in names(Partials)){
  eval(parse(text=paste0( 'Narrow$', Gene, ' <- vector()' )))
  #OK#_eval(parse(text=paste0( 'Keepz <- Candidates$', Gene, '[ Candidates$', Gene, '$MEAN > 0.01, ]' )))

  #OK#_eval(parse(text=paste0( 'Keepz <- Candidates$', Gene, '[ Candidates$', Gene, '$MEAN > 0.004, ]' )))
  eval(parse(text=paste0( 'Keepz <- Candidates$', Gene, '[ Candidates$', Gene, '$MEAN > 0.1, ]' )))
  #eval(parse(text=paste0( 'Keepz <- Candidates$', Gene, '[ Candidates$', Gene, '$MEAN > 0.002, ]' )))
  Keepz <- Keepz[ complete.cases(Keepz),]
  Keeps <- Keepz$ensembl_gene_id
  
  for(Tissue in names( ExpressionDS ) ){
    eval(parse(text=paste0( 'Tarz <- colnames(Partials$', Gene,'$', Tissue,')[ colnames(Partials$', Gene,'$', Tissue,') %in% Keeps]')))
    
    #eval(parse(text=paste0('TarENS <- Candidates$', Gene, '[ Candidates$', Gene, '$hgnc_symbol == \'', Gene, '\' ,]$ensembl_gene_id' )))
    eval(parse(text=paste0( 'Lookup <- Partials$', Gene,'$', Tissue, '[ Partials$', Gene,'$', Tissue, '[,\'SeedGene\'] == \'', Tarz, '\', Tarz ]' )))
     
    eval(parse(text=paste0( 'Narrow$', Gene, ' <- c( Narrow$', Gene, ', names( Lookup))' )))
  }
  eval(parse(text=paste0( 'Narrow$', Gene, ' <- Narrow$', Gene, '[ !duplicated(Narrow$', Gene, ')]' )))
}

##Isolate Narrow Partials Or not.. 
NewPartials <- list()
for( Gene in names(Partials)){
  eval(parse(text=paste0( 'NewPartials$', Gene, ' <- list()' )))
  for(Tissue in names( ExpressionDS ) ){
    eval(parse(text=paste0('NewPartials$', Gene, '$', Tissue, ' <-  Partials$', Gene, '$', Tissue, '[ Partials$', Gene, '$', Tissue, '[,\'SeedGene\'] %in% Narrow$', Gene, ', ]')))
    #eval(parse(text=paste0('NewPartials$', Gene, '$', Tissue, ' <- Partials$', Gene, '$', Tissue)))
  }
}

####Only keep genes with all 6 tissue correlations
for( Gene in names(NewPartials)){
  if( is.matrix( eval(parse(text=paste0('NewPartials$', Gene, '$', Tissue ))) ) ){
    eval(parse(text=paste0( 'foo <- c( NewPartials$', Gene, '$DLPFC[,\'SeedGene\'], NewPartials$', Gene, '$TCX[,\'SeedGene\'], NewPartials$', Gene, '$FP[,\'SeedGene\'], NewPartials$', Gene, '$IFG[,\'SeedGene\'], NewPartials$', Gene, '$STG[,\'SeedGene\'], NewPartials$', Gene, '$PHG[,\'SeedGene\'])')))
  }else{
    eval(parse(text=paste0( 'foo <- c( NewPartials$', Gene, '$DLPFC[\'SeedGene\'], NewPartials$', Gene, '$TCX[\'SeedGene\'], NewPartials$', Gene, '$FP[\'SeedGene\'], NewPartials$', Gene, '$IFG[\'SeedGene\'], NewPartials$', Gene, '$STG[\'SeedGene\'], NewPartials$', Gene, '$PHG[\'SeedGene\'])')))
  }
  foo <- foo[ !duplicated(foo) ]
  Tib <- rep(0, length(foo))
  names(Tib) <- foo

  for(Tissue in names( ExpressionDS ) ){
    if( is.matrix( eval(parse(text=paste0('NewPartials$', Gene, '$', Tissue ))) ) ){
      eval(parse(text=paste0( 'Tib[ NewPartials$', Gene, '$', Tissue, '[ ,\'SeedGene\' ]] <- Tib[ NewPartials$', Gene, '$', Tissue, '[ ,\'SeedGene\' ]] + 1')))
    }else{
      eval(parse(text=paste0( 'Tib[ NewPartials$', Gene, '$', Tissue, '[ \'SeedGene\' ]] <- as.numeric( Tib[ NewPartials$', Gene, '$', Tissue, '[ \'SeedGene\' ]]) + 1')))
    }
  }
  for(Tissue in names( ExpressionDS ) ){
      if( is.matrix( eval(parse(text=paste0('NewPartials$', Gene, '$', Tissue ))) ) ){
        eval(parse(text=paste0( 'NewPartials$', Gene, '$', Tissue, '<- NewPartials$', Gene, '$', Tissue, '[ NewPartials$', Gene, '$', Tissue, '[ ,\'SeedGene\' ] %in% names(Tib[Tib>3]),]')))
      }else{
        eval(parse(text=paste0( 'NewPartials$', Gene, '$', Tissue, ' <- NewPartials$', Gene, '$', Tissue, '[ NewPartials$', Gene, '$', Tissue, '[ \'SeedGene\' ] %in% names(Tib[Tib>3])]')))
        eval(parse(text=paste0( 'NewPartials$', Gene, '$', Tissue, ' <- t(as.matrix( NewPartials$', Gene, '$', Tissue, '))')))
      }
  }
} 

Cuts <- matrix(0, 101,length(names(Partials)))
colnames( Cuts ) <- names(Partials)
row.names( Cuts ) <-  seq( from=0, to=10, by=.1 ) 

mark<-Sys.time()
#_#Target <- list()
Y <- foreach( i=row.names( Cuts ), .combine=rbind ) %dopar% {
  Tar <- vector()
  Target <- list()
  for( Gene in names(NewPartials)){
  #_#eval(parse(text=paste0( 'Target$', Gene, ' <- vector()' )))
  #foreach( i=row.names( Cuts ), .combine=rbind ) %dopar% {
    #_#
    eval(parse(text=paste0( 'Target$', Gene, ' <- vector()' )))
    #_#
    for( Tissue in eval(parse(text=paste0( 'names(NewPartials$', Gene, ')'  ))) ){
      Temp <- eval(parse(text=paste0( 'NewPartials$', Gene, '$', Tissue )))
  
      if( dim(Temp)[1] > 1 ){
        row.names(Temp) <- Temp[, 'SeedGene']
        Temp <- as.data.frame( Temp[ ,(colnames(Temp) %in% 'SeedGene') == F ] )
        Temp[] <- lapply(Temp, function(x) as.numeric(as.character(x)))
      }else{
        #row.names(Temp) <- as.character( Temp[, 'SeedGene'] )
        Cs<-as.character( Temp[, 'SeedGene'] )
        Temp <- as.data.frame( Temp[ ,(colnames(Temp) %in% 'SeedGene') == F ] )
        Rs <- row.names(Temp)
        Temp <- data.table::transpose(Temp)
        row.names(Temp) <- Cs
        colnames(Temp) <- Rs
        
        Temp[] <- lapply(Temp, function(x) as.numeric(as.character(x)))
      }
  
      for( RName in row.names(Temp) ){
        Selct <- Temp[ RName, Temp[ RName, ]>0 ]
        Vals <- as.vector( as.numeric(as.character( Selct[ 1 , Selct[1,] < 1 ] ) ))
        Vals <- c( Vals, -1*Vals )
        M <- mean( Vals )
        S <- sd( Vals )
        Lim <- M+as.numeric(i)*S
        Adds <- colnames( Selct[ , Selct > Lim ] )
        #Throw in any genes with more than 1 Parital corelation to the core set
       # if( dim(Temp)[1] > 1){
       #   Adds <- c(Adds, names(Temp[, colSums(Temp != 0) > 2 ]) )
        #  Adds <- Adds[ !duplicated(Adds) ]
        #}
        eval(parse(text=paste0( 'Target$', Gene, ' <- c(Target$', Gene, ', Adds)'  )))
      }
    }
    #Log Gene Lengths
    
    
  } 
  for(Ok in names(NewPartials)){
      eval(parse(text=paste0( 'LENG <-length(Target$', Ok, '[!duplicated(Target$', Ok, ')])'  )))
      eval(parse(text=paste0(  'Tar <- c(Tar, ',  LENG,')')))
  }
    names(Tar) <- names(NewPartials)
    Extra <- 'StDevs'
    eval(parse(text=paste0(  'Tar[\'', Extra, '\'] <- ',  i)))
    return( Tar )
}
Sys.time()-mark
#Narrow_sink <- Y
data.table::fwrite(Y, file='NarrowPartial_Expanded_Numbers.csv', row.names=F, col.names=T)

APOC1_Names <- list()
for(Tissue in names(NewPartials$APOC1) ){
  eval(parse(text=paste0('foo <- NewPartials$APOC1$', Tissue)))
  row.names( foo ) <- foo[,'SeedGene']
  foo <- foo[ , (colnames(foo) %in% 'SeedGene') == F ]
  foo <- as.data.frame(foo)
  foo[] <- lapply(foo, function(x) as.numeric(as.character(x)))

  Count <- do.call( rbind, lapply(foo, function(x){ length(which(x==0))/length(x)}))
  eval(parse(text=paste0('APOC1_Names$',Tissue ,' <- names(Count[ Count < 0.76,])')))
}

foo <- c( APOC1_Names$DLPFC, APOC1_Names$TCX, APOC1_Names$FP, APOC1_Names$IFG, APOC1_Names$STG, APOC1_Names$PHG )
length( foo )

poo <- names( table(foo)[table(foo)>1] )
moo <-   NewPartials$APOC1$DLPFC[,"SeedGene"]     
      
PLOT_y <- reshape::melt(as.data.frame(Y), id=c("StDevs") )
colnames(PLOT_y) <- c( "StDevs", "Seed Gene", "value" )
library(ggplot2)


###Should I Look only at genes correlated with target gene??

#10% of the targets remaining at the second Standard Deviation
CutoffVal <- round( Y[18,1:8]/10 )
LIN <- rep(0, length(names(CutoffVal)))
names(LIN) <- names(CutoffVal)
for(tar in names(CutoffVal)){
  eval(parse(text=paste0( 'LIN[\'', tar, '\'] <- Y[ Y[,\'', tar, '\'] < CutoffVal[tar], ][1,\'StDevs\']')))
}

LIN <- as.data.frame(LIN)
LIN$`Seed Gene` <- row.names(LIN)
#LIN$LIN <-c( 1, 1, 1, 1, 1, 1 )
LIN$LIN <- c( 0.7, 1.3, 1.3, 1.3, 1.3, 1.7, 1.3, 1.3)

g <- ggplot( data=PLOT_y, aes( x=StDevs, y=value, col=`Seed Gene`)) + 
  geom_point() + 
  geom_line() +
  geom_vline(data = LIN, aes(xintercept = LIN, col=`Seed Gene`),linetype='dashed' ) +
  ylab("Partially Correlated Genes Included") +
  xlab("Standard Deviation Cutoff")

ggsave(g, file="Cutoffs.eps", device="eps")
system('synapse store --parentid syn21818446 --name Partial_Correlation_Decay Cutoffs.eps')
g

###Find Top 200 Targets:
REF <- c( 0.7, 1.3, 1.3, 1.3, 1.3, 1.7, 1.3, 1.3 )
names( REF ) <- names(NewPartials)

Target <- list()
for( Gene in names(NewPartials)){
  eval(parse(text=paste0( 'Target$', Gene, ' <- vector()' )))
  for( Tissue in eval(parse(text=paste0( 'names(NewPartials$', Gene, ')'  ))) ){
    Temp <- eval(parse(text=paste0( 'NewPartials$', Gene, '$', Tissue )))
    Rs <- Temp[,'SeedGene']
    row.names(Temp) <- Temp[, 'SeedGene']
    Temp <- as.data.frame( Temp[ ,(colnames(Temp) %in% 'SeedGene') == F ] )
    Temp[] <- lapply(Temp, function(x) as.numeric(as.character(x)))
     #Selct <- Temp[ RName, Temp[ RName, ]>0 ]
    if( dim(Temp)[2] > 1 ){
      
    }else{
      Cs<-row.names(Temp)
      Temp <- data.table::transpose(Temp)
      row.names(Temp) <- Rs
      colnames(Temp) <- Cs
    }
    for( RName in row.names(Temp) ){
     
      Selct <- Temp[ RName, Temp[ RName, ]>0 ]

      Vals <- as.vector( as.numeric(as.character( Selct[ 1 , Selct[1,] < 1 ] ) ))
      Vals <- c( Vals, -1*Vals )
      M <- mean( Vals )
      S <- sd( Vals )
      #Lim <- M + as.numeric( LIN[ Gene,]$LIN )*S
      FIND <- Y[ ,c(Gene,"StDevs")][ Y[ ,c(Gene,"StDevs")][,1] > 200, ]
      SDs <- FIND[ dim(FIND)[1], 2]
      
      #if( Gene %in% c( "TREM2")){
        #SDs <- 0.7
      #}else{
        #if( Gene %in% c( 'APOC1')){
          #SDs <- 1.7
        #}else{
          #SDs <- 1.3
        #}
      #}
      if( Gene %in% c( "EED")){
        SDs <- 0.5
      }else{
        if( Gene %in% c( "KNOP1")){
          SDs <- 0.8
        }else{
          if( Gene %in% c( 'MTCH2') ){
            #SDs <- 0.5
            SDs <- 0.4
            #SDs <- 1.5
          }else{
            if( Gene %in% c( 'TREM2')){
              SDs <- 1.4
            }else{
              SDs <- 1.5
            }
          }
        }
      }
      Lim <- M + SDs*S
      Adds <- colnames( Selct[ , Selct > Lim ] )
      eval(parse(text=paste0( 'Target$', Gene, ' <- c(Target$', Gene, ', Adds)'  )))
    }
  }
}

for( RName in names(Target) ){
   eval(parse(text=paste0( 'Target$', RName, ' <- Target$', RName, '[!duplicated(Target$', RName, ')]'  )))
}

#```
#```{r EnrichR}

library(enrichR)
dbs <- listEnrichrDbs()

dbs <- c("GO_Molecular_Function_2018", 
         "WikiPathways_2019_Human",
         "GO_Cellular_Component_2018",
         "GO_Biological_Process_2018") #, "ProteomicsDB_2020", "KEGG_2019_Human", "DSigDB","TRRUST_Transcription_Factors_2019")

mart <- useMart("ensembl", host="grch37.ensembl.org", dataset = "hsapiens_gene_ensembl")

TargetGN <- list()
ENRICH <- list()

Total_Genes <- c( colnames( Partials$TREM2$DLPFC ),
                  colnames( Partials$TREM2$FP ),
                  colnames( Partials$TREM2$IFG ),
                  colnames( Partials$TREM2$PHG ),
                  colnames( Partials$TREM2$STG ),
                  colnames( Partials$TREM2$TCX )
)
#Take only genes in all expression sets:
Total_Genes <- names(table(Total_Genes)[ table(Total_Genes) == 6])                  
Total_Genes <- Total_Genes[ (Total_Genes == 'SeedGene') == F ]

TG <- getBM(filters = 'ensembl_gene_id', attributes = c('ensembl_gene_id', 'hgnc_symbol'), values = Total_Genes, mart = mart)
TG <- TG[ TG$ensembl_gene_id !='ENSG00000265354',] 
TG$Tot <- paste0( TG$ensembl_gene_id, '_', TG$hgnc_symbol )
TG <- TG[ !duplicated(TG$Tot), ]
TG <- TG[ TG$hgnc_symbol != "", ]
row.names(TG) <- TG$hgnc_symbol

Locked_TG <- as.data.frame(TG$hgnc_symbol)
Locked_TG$Included <- 0
names(Locked_TG) <- c( "Gene", "Included" )
Locked_TG$Gene <- as.character( Locked_TG$Gene ) 
row.names(Locked_TG) <- Locked_TG$Gene

Locked_TG <- Locked_TG[ Locked_TG$Gene != 'NA', ]

for( G in names(Target)){
  eval(parse(text=paste0( 'Genes <- getBM(filters = \'ensembl_gene_id\', attributes = c(\'ensembl_gene_id\', \'hgnc_symbol\'), values = Target$', G, ', mart = mart)' )))
  
  GN <- Genes[ (Genes$hgnc_symbol %in% "") ==F,]$hgnc_symbol
  eval(parse(text=paste0('TargetGN$', G, ' <-  Genes[ (Genes$hgnc_symbol %in% "") ==F,]$hgnc_symbol')))
  
  eval(parse(text=paste0('Locked_TG[TargetGN$', G, ',]$Included <- 1')))
  #foo<- enrichr(Locked_TG, dbs)
  eval(parse(text=paste0('ENRICH$', G, ' <-  enrichr( Locked_TG[ Locked_TG$Included ==1,]$Gene, dbs)')))
  
  Locked_TG$Included <- 0
}
#TMP <- enrichr( GN, dbs)
for( G in names(Target)){
  for( version in dbs ){
    eval(parse(text=paste0( 'temp <- ENRICH$', G, '$', version )))
    temp <- temp[ temp$Adjusted.P.value < 0.05, ]
    eval(parse(text=paste0( 'ENRICH$', G, '$', version, ' <- temp' )))
  }
} 

```
```{r clusterP}

parentId = 'syn18936948';
activityName = 'Gene Set Enrichment';
activityDescription = 'Figure 4: gene set enrichment of genes implicated in TWAS regions';
thisFileName <- 'GeneSet_Expansion.Rmd'
# Github link
thisRepo <- githubr::getRepo(repository = "jgockley62/TWAS", ref="branch", refName='master')
thisFile <- githubr::getPermlink(repository = thisRepo, repositoryPath=paste0('code/',thisFileName))

CODE <- syn_temp$store(synapseclient$Folder(name = "Gene Set Enrichment Plots", parentId = parentId))

library( clusterProfiler )
library(enrichplot)
library(enrichR)

Enrich_Run <- function( cutoffs ){
  #'@cutoffs a named vector of SD cutoff valutes for genes
  SD_Store <- rep(NA,length(names(NewPartials)))
  names(SD_Store) <- names(NewPartials)
  
  Target <- list()
  for( Gene in names(NewPartials)){
    eval(parse(text=paste0( 'Target$', Gene, ' <- vector()' )))
    for( Tissue in eval(parse(text=paste0( 'names(NewPartials$', Gene, ')'  ))) ){
      Temp <- eval(parse(text=paste0( 'NewPartials$', Gene, '$', Tissue )))
      Rs <- Temp[,'SeedGene']
      row.names(Temp) <- Temp[, 'SeedGene']
      Temp <- as.data.frame( Temp[ ,(colnames(Temp) %in% 'SeedGene') == F ] )
      Temp[] <- lapply(Temp, function(x) as.numeric(as.character(x)))
       #Selct <- Temp[ RName, Temp[ RName, ]>0 ]
      if( dim(Temp)[2] > 1 ){
        
      }else{
        Cs<-row.names(Temp)
        Temp <- data.table::transpose(Temp)
        row.names(Temp) <- Rs
        colnames(Temp) <- Cs
      }
      for( RName in row.names(Temp) ){
       
        Selct <- Temp[ RName, Temp[ RName, ]>0 ]
  
        Vals <- as.vector( as.numeric(as.character( Selct[ 1 , Selct[1,] < 1 ] ) ))
        Vals <- c( Vals, -1*Vals )
        M <- mean( Vals )
        S <- sd( Vals )
        #Lim <- M + as.numeric( LIN[ Gene,]$LIN )*S
        FIND <- Y[ ,c(Gene,"StDevs")][ Y[ ,c(Gene,"StDevs")][,1] > 200, ]
        SDs <- FIND[ dim(FIND)[1], 2]
        
        eval( parse( text = paste0( 'SDs <- cutoffs[\'', Gene,'\']' )))
        eval( parse( text = paste0( 'SD_Store[\'', Gene,'\'] <- ', SDs )))
        Lim <- M + SDs*S
        Adds <- colnames( Selct[ , Selct > Lim ] )
        eval(parse(text=paste0( 'Target$', Gene, ' <- c(Target$', Gene, ', Adds)'  )))
      }
    }
  }
  
  for( RName in names(Target) ){
     eval(parse(text=paste0( 'Target$', RName, ' <- Target$', RName, '[!duplicated(Target$', RName, ')]'  )))
  }
  
  organism = "org.Hs.eg.db"
  #BiocManager::install(organism, character.only = TRUE)
  library(organism, character.only = TRUE)
  library(DOSE)
  
  Enrich_PLOTS <- list()
  for( G in names(Target)){
    
    
    eval(parse(text=paste0( 'Genes <- getBM(filters = \'ensembl_gene_id\', attributes = c(\'ensembl_gene_id\', \'hgnc_symbol\'), values = Target$', G, ', mart = mart)' )))
    
    GN <- Genes[ (Genes$hgnc_symbol %in% "") ==F,]$hgnc_symbol
  eval(parse(text=paste0('TargetGN$', G, ' <-  Genes[ (Genes$hgnc_symbol %in% "") ==F,]$hgnc_symbol')))
    
    eval(parse(text=paste0('Locked_TG[TargetGN$', G, ',]$Included <- 1')))
    
    eval(parse(text=paste0( 'Genes <- getBM(filters = \'ensembl_gene_id\', attributes = c(\'ensembl_gene_id\', \'hgnc_symbol\', \'entrezgene_id\'), values = Target$', G, ', mart = mart)' )))
  
    #Locked_TG$Gene
  
    #sample_test <- enrichGO( Genes$entrezgene_id, OrgDb=organism, pvalueCutoff=1, qvalueCutoff=1)
  
    Locked_TG$ENSG <- TG[ Locked_TG$Gene, ]$ensembl_gene_id
    gene.df <- bitr( Locked_TG$ENSG, fromType = "ENSEMBL", toType = c("ENSEMBL", "SYMBOL", "ENTREZID"), OrgDb = org.Hs.eg.db)
    gene.df$Tot <- paste0( gene.df$ENSEMBL, "_", gene.df$SYMBOL, "_", gene.df$ENTREZID )
    #'select()' returned 1:many mapping between keys and columns
    #1.91% of input gene IDs are fail to map...
  
    Gsubset <- eval(parse(text=paste0('Target$', G )))
    Gsubset <- Gsubset[ Gsubset %in% gene.df$ENSEMBL ]
    ego <- enrichGO(gene          = Gsubset,
                  universe      = gene.df$ENSEMBL,
                  OrgDb         = org.Hs.eg.db,
                  #keyType       = 'SYMBOL',
                  keyType       = 'ENSEMBL',
                  ont           = "ALL",
                  pAdjustMethod = "BH",
                  pvalueCutoff  = 0.01,
                  qvalueCutoff  = 0.05
                )
    
    eval(parse(text=paste0( 'SD_Used <- as.numeric(cutoffs[\'', G, '\'])' )))
    if( dim(as.data.frame(ego))[1] >1 ){
      cluster_summary <- data.frame(ego)
      write.csv(cluster_summary , file = paste0("EnrichmentResults_", G, "_Stdevs_", SD_Used,".csv"), row.names=FALSE)
      
      ENRICH_OBJ <-  syn_temp$store( synapseclient$File( path=paste0("EnrichmentResults_", G, "_Stdevs_", SD_Used,".csv"), name = paste0("EnrichmentResults_", G, "_Stdevs_", SD_Used), parentId=CODE$properties$id ), activityName = activityName, executed = thisFile, activityDescription = activityDescription)
      
      eval(parse(text=paste0( 'Enrich_PLOTS$', G, ' <- list()')))
      # Dotplot
      eval(parse(text=paste0( 'Enrich_PLOTS$', G, '$Dot <- clusterProfiler::dotplot(ego, x = "GeneRatio", showCategory=30)' )))
      pdf(file = paste0("EnrichmentDotPlot_", G, "_Stdevs_", SD_Used,".pdf"), width = 14, height = 7)
         print( clusterProfiler::dotplot(ego, x = "GeneRatio", showCategory=30) )
      dev.off()
  
      ENRICH_OBJ <-  syn_temp$store( synapseclient$File( path=paste0("EnrichmentDotPlot_", G, "_Stdevs_", SD_Used,".pdf"), name = paste0("EnrichmentDotPlot_", G, "_Stdevs_", SD_Used), parentId=CODE$properties$id ), activityName = activityName, executed = thisFile, activityDescription = activityDescription)
  
      # Net Plot
      eval(parse(text=paste0( 'Enrich_PLOTS$', G, '$Net <- cnetplot(ego, foldChange=NULL)' )))
      
      pdf(file = paste0("EnrichmentNetPlot_", G, "_Stdevs_", SD_Used,".pdf"), width = 7, height = 7)
         print( cnetplot(ego, foldChange=NULL))
      dev.off()
      
      ENRICH_OBJ <-  syn_temp$store( synapseclient$File( path=paste0("EnrichmentNetPlot_", G, "_Stdevs_", SD_Used,".pdf"), name = paste0("EnrichmentNetPlot_", G, "_Stdevs_", SD_Used), parentId=CODE$properties$id ), activityName = activityName, executed = thisFile, activityDescription = activityDescription)
  
      # Enrichment Plot
      eval(parse(text=paste0( 'Enrich_PLOTS$', G, '$Erich <- enrichplot::emapplot(ego, showCategory = 10)' )))
      
      pdf(file = paste0("EnrichmentEnrichPlot_", G, "_Stdevs_", SD_Used,".pdf"), width = 7, height = 7)
        print( enrichplot::emapplot(ego, showCategory = 10) )
      dev.off()
      
      ENRICH_OBJ <-  syn_temp$store( synapseclient$File( path=paste0("EnrichmentEnrichPlot_", G, "_Stdevs_", SD_Used,".pdf"), name = paste0("EnrichmentEnrichPlot_", G, "_Stdevs_", SD_Used,".pdf"), parentId=CODE$properties$id ), activityName = activityName, executed = thisFile, activityDescription = activityDescription)
  
    }else{}
  }
}

#Run Enrichment at Broad Cutoffs:
input <- c( TREM2 = 0.8, 
            CD2AP= 0.8, 
            MTCH2= 0.8, 
            EED= 0.8, 
            KNOP1= 0.8, 
            APOC1= 0.8,
            CEACAM19= 0.8,
            CLPTM1= 0.8
          )
Enrich_Run( input )

#Run Enrichment at Narrow Cutoffs:
input <- c( TREM2 = 2.8, 
            CD2AP = 2.8, 
            MTCH2 = 2.8, 
            EED = 2.8, 
            KNOP1 = 2.8, 
            APOC1 = 2.8,
            CEACAM19= 2.8,
            CLPTM1= 2.8
          )
Enrich_Run( input )

#Run Enrichment at Custom Cutoffs:
input <- c( TREM2 = 0.8, 
            #CD2AP = 2, 
            CD2AP = 1,
            MTCH2 = 0.4, 
            EED = 2, 
            KNOP1 = 2, 
            APOC1 = 1.7,
            CEACAM19= 2,
            CLPTM1= 2
          )
Enrich_Run( input )
#if( Gene %in% c( "TREM2")){
          #SDs <- 0.7
          #SDs <- 2.8
        #}else{
          #if( Gene %in% c( 'APOC1')){
            #SDs <- 1.7
            #SDs <- 2.8
          #}else{
            #SDs <- 1.3
            #SDs <- 2.8
          #}
        #}
        #if( Gene %in% c( "EED")){
          #SDs <- 0.5
        #}else{
          #if( Gene %in% c( "KNOP1")){
           # SDs <- 0.8
          #}else{
            #if( Gene %in% c( 'MTCH2') ){
              #SDs <- 0.5
              #SDs <- 0.4
              #SDs <- 1.5
            #}else{
              #if( Gene %in% c( 'TREM2')){
                #SDs <- 1.4
              #}else{
                #SDs <- 1.5
              #}
            #}
          #}
        #}

```


```{r CellTypeSpecificity}
Lake <- read.csv( file=syn_temp$get('syn21563069')$path, header = T )
Lake <- as.data.frame( data.table::fread( file=syn_temp$get('syn21563069')$path ) )

Total_Genes <- c( colnames( Partials$TREM2$DLPFC ),
                  colnames( Partials$TREM2$FP ),
                  colnames( Partials$TREM2$IFG ),
                  colnames( Partials$TREM2$PHG ),
                  colnames( Partials$TREM2$STG ),
                  colnames( Partials$TREM2$TCX )
)
#Take only genes in all expression sets:
Total_Genes <- names(table(Total_Genes)[ table(Total_Genes) == 6])                  
Total_Genes <- Total_Genes[ (Total_Genes == 'SeedGene') == F ]

mart <- useMart("ensembl", host="grch37.ensembl.org", dataset = "hsapiens_gene_ensembl")
genes <- Lake$Gene
Lake_genes <- getBM(filters = 'hgnc_symbol', attributes = c('ensembl_gene_id', 'hgnc_symbol'), values = genes, mart = mart)
Lake_genes$Tot <- paste0( Lake_genes$ensembl_gene_id, "_", Lake_genes$hgnc_symbol )
Lake_genes <- Lake_genes[ !duplicated(Lake_genes$Tot), ]
row.names(Lake_genes) <- Lake_genes$ensembl_gene_id

#filter for Lake Et. Al genes in RNA-Seq
Lake_genes <- Lake_genes[ Lake_genes$ensembl_gene_id %in% Total_Genes,]
#row.names(Lake_genes) <- Lake_genes$hgnc_symbol

#TIMM23B entry Mis-named ENSG as TIMM23:
Lake_genes[ Lake_genes$Tot == 'ENSG00000265354_TIMM23B', ]$ensembl_gene_id <- "ENSG00000204152"
Lake_genes[ Lake_genes$Tot == 'ENSG00000265354_TIMM23B', ]$Tot <- "ENSG00000204152_TIMM23B"
Lake_genes <- Lake_genes[ !duplicated(Lake_genes$Tot), ]
row.names(Lake_genes) <- Lake_genes$hgnc_symbol

#Add ENSGs to Lake data:
Lake$ENSG <- Lake_genes[ Lake$Gene, ]$ensembl_gene_id

#Throw out Lake Genes not able to be translated: 4.74%
Lake <- Lake[grepl('ENSG', Lake$ENSG)==T,]

#Cell_type ENSG List
CellTypeGenes <- list()
for( Name in names(table(Lake$Cluster)) ){
  eval(parse(text=paste0( 'CellTypeGenes$', Name, ' <- Lake[ Lake$Cluster == \'', Name,'\',]$ENSG' )))
}

#Re-Define Partial Cor Gene Sets:
GSE_Target <- list()
for( Gene in names(NewPartials)){
  eval(parse(text=paste0( 'GSE_Target$', Gene, ' <- vector()' )))
  for( Tissue in eval(parse(text=paste0( 'names(NewPartials$', Gene, ')'  ))) ){
    Temp <- eval(parse(text=paste0( 'NewPartials$', Gene, '$', Tissue )))
    Rs <- Temp[,'SeedGene']
    row.names(Temp) <- Temp[, 'SeedGene']
    Temp <- as.data.frame( Temp[ ,(colnames(Temp) %in% 'SeedGene') == F ] )
    Temp[] <- lapply(Temp, function(x) as.numeric(as.character(x)))
     #Selct <- Temp[ RName, Temp[ RName, ]>0 ]
    if( dim(Temp)[2] > 1 ){
      
    }else{
      Cs<-row.names(Temp)
      Temp <- data.table::transpose(Temp)
      row.names(Temp) <- Rs
      colnames(Temp) <- Cs
    }
    for( RName in row.names(Temp) ){
     
      Selct <- Temp[ RName, Temp[ RName, ]>0 ]

      Vals <- as.vector( as.numeric(as.character( Selct[ 1 , Selct[1,] < 1 ] ) ))
      Vals <- c( Vals, -1*Vals )
      M <- mean( Vals )
      S <- sd( Vals )
      #Lim <- M + as.numeric( LIN[ Gene,]$LIN )*S
      FIND <- Y[ ,c(Gene,"StDevs")][ Y[ ,c(Gene,"StDevs")][,1] > 200, ]
      SDs <- FIND[ dim(FIND)[1], 2]
      if( Gene %in% c( "TREM2")){
        SDs <- 0.7
      }else{
        if( Gene %in% c( 'APOC1')){
          SDs <- 1.7
        }else{
          SDs <- 1.3
        }
      }
      Lim <- M + SDs*S
      Adds <- colnames( Selct[ , Selct > Lim ] )
      eval(parse(text=paste0( 'GSE_Target$', Gene, ' <- c(GSE_Target$', Gene, ', Adds)'  )))
    }
  }
}

# Cell Type enrichment by binomial test:
Actuals_Pval <- as.data.frame( matrix( 0, length( names(GSE_Target) ), length( names(CellTypeGenes) )) )
colnames(Actuals_Pval) <- names(CellTypeGenes) 
row.names(Actuals_Pval) <- names(GSE_Target)
Actuals_OR <- Actuals_Pval

for( G in names(GSE_Target)){
  eval(parse(text=paste0( 'N <- length( GSE_Target$', G, ')')))
  eval(parse(text=paste0( 'Genes <- GSE_Target$', G )))
  Genes <- Genes[ (Genes %in% Total_Genes) == T ]
  #Calc Actual Overlap
  for( CT in colnames(Actuals_Pval) ){
    #eval(parse(text=paste0( 'Actuals[ \'', G,'\',\'', CT,'\'] <- as.numeric( table( Genes %in% CellTypeGenes$', CT, ')[\'TRUE\'])')))
    eval(parse(text=paste0( 'Perc <- length(CellTypeGenes$', CT, ')/length( Total_Genes )')))
    eval(parse(text=paste0( 'Emp_Perc <- as.numeric( table( Genes %in% CellTypeGenes$', CT, ')[\'TRUE\'])/length( Genes )')))
    
    if( length( eval(parse(text=paste0('table(Genes %in% CellTypeGenes$', CT, ')' ))) ) > 1 ){ 
      eval(parse(text=paste0( 'N <- as.numeric( table( Genes %in% CellTypeGenes$', CT, ')[\'TRUE\'])' )))
      eval(parse(text=paste0( 'SIZE <- length( CellTypeGenes$', CT, ')' )))
      
      Foo <- binom.test( x=N, n=SIZE, p=Perc, alternative = c("two.sided") )
      #Poo <- prop.test(x=N, n=SIZE, p=Perc, alternative = "two.sided", correct = TRUE)
      
      if( Emp_Perc > Perc ){
        OR <- Emp_Perc/Perc
      }else{
        OR <- -1*( Perc/Emp_Perc )
      }
      #Foo$p.value
      
      eval(parse(text=paste0( 'Actuals_Pval[ \'', G,'\',\'', CT,'\'] <- Foo$p.value')))
      eval(parse(text=paste0( 'Actuals_OR[ \'', G,'\',\'', CT,'\'] <- OR')))
    }else{
      Emp_Perc <- 0
      eval(parse(text=paste0( 'N <- 0' )))
      eval(parse(text=paste0( 'SIZE <- length( CellTypeGenes$', CT, ')' )))
      
      Foo <- binom.test( N, SIZE, Perc )
      if( Emp_Perc == 0){
        OR <- NA
      }else{
        if( Emp_Perc > Perc ){
          OR <- Emp_Perc/Perc
        }else{
          OR <- -1*( Perc/Emp_Perc )
        }
      }
      eval(parse(text=paste0( 'Actuals_Pval[ \'', G,'\',\'', CT,'\'] <- Foo$p.value')))
      eval(parse(text=paste0( 'Actuals_OR[ \'', G,'\',\'', CT,'\'] <- OR')))
    }
  }
  Leng <- dim( Actuals_Pval )[2]
  eval(parse(text=paste0( 'Actuals_Pval[ \'', G, '\', ] <- p.adjust(Actuals_Pval[ \'', G, '\', ], method = \'fdr\', n = ', Leng,' )' )))
}

test_labels <- Actuals_Pval
test_labels[ test_labels< 0.05] <- "*"
test_labels[ test_labels > 0.05] <- ""


lin <- LIN
lin$LIN <- c( 0.7, 1.3,1.3,1.3,1.3,1.7,1.3,1.3 )
gG <- ggplot( data=PLOT_y, aes( x=StDevs, y=value, col=`Seed Gene`)) + 
  geom_point() + 
  geom_line() +
  geom_vline(data = lin, aes(xintercept = LIN, col=`Seed Gene`),linetype='dashed' ) +
  ylab("Partially Correlated Genes Included") +
  xlab("Standard Deviation Cutoff")

gG


library(RColorBrewer)
library(grDevices)
cols <- colorRampPalette(c( "deepskyblue4", "darkslategray2", "white", "darkgoldenrod2", "red"))(100)

Lake_HeatMap <- pheatmap::pheatmap( as.matrix(Actuals_OR), col=cols, cluster_cols=F, 
                    display_numbers = test_labels, fontsize_number=40)



save_pheatmap_pdf <- function(x, filename, width=7, height=7) {
   stopifnot(!missing(x))
   stopifnot(!missing(filename))
   pdf(filename, width=width, height=height)
   grid::grid.newpage()
   grid::grid.draw(x$gtable)
   dev.off()
}

save_pheatmap_pdf(Lake_HeatMap, "Lake_HeatMap.pdf")

```
```{r CellTypeSpecificity_Mathys}
Mathy <- read.csv( file=syn_temp$get('syn21785650')$path, header = T )
#Mathy <- as.data.frame( data.table::fread( file=syn_temp$get('syn21563069')$path ) )

Total_Genes <- c( colnames( Partials$TREM2$DLPFC ),
                  colnames( Partials$TREM2$FP ),
                  colnames( Partials$TREM2$IFG ),
                  colnames( Partials$TREM2$PHG ),
                  colnames( Partials$TREM2$STG ),
                  colnames( Partials$TREM2$TCX )
)
#Take only genes in all expression sets:
Total_Genes <- names(table(Total_Genes)[ table(Total_Genes) == 6])                  
Total_Genes <- Total_Genes[ (Total_Genes == 'SeedGene') == F ]

mart <- useMart("ensembl", host="grch37.ensembl.org", dataset = "hsapiens_gene_ensembl")
genes <- Mathy$gene.name
Mathy_genes <- getBM(filters = 'hgnc_symbol', attributes = c('ensembl_gene_id', 'hgnc_symbol'), values = genes, mart = mart)

Mathy_genes$Tot <- paste0( Mathy_genes$ensembl_gene_id, "_", Mathy_genes$hgnc_symbol )
Mathy_genes <- Mathy_genes[ !duplicated(Mathy_genes$Tot), ]
row.names(Mathy_genes) <- Mathy_genes$ensembl_gene_id

#filter for Mathys Et. Al genes in RNA-Seq
Mathy_genes <- Mathy_genes[ Mathy_genes$ensembl_gene_id %in% Total_Genes,]
row.names(Mathy_genes) <- Mathy_genes$hgnc_symbol

#Add ENSGs to Lake data:
Mathy$ENSG <- Mathy_genes[ Mathy$gene.name, ]$ensembl_gene_id

#Throw out Mathys Genes not able to be translated: 3.78%
Mathy <- Mathy[grepl('ENSG', Mathy$ENSG)==T,]

#Cell_type ENSG List
CellTypeGenes <- list()
for( Name in names(table(Mathy$subpopulation)) ){
  eval(parse(text=paste0( 'CellTypeGenes$', Name, ' <- Mathy[ Mathy$subpopulation == \'', Name,'\',]$ENSG' )))
}

#Re-Define Partial Cor Gene Sets:
GSE_Target <- list()
for( Gene in names(NewPartials)){
  eval(parse(text=paste0( 'GSE_Target$', Gene, ' <- vector()' )))
  for( Tissue in eval(parse(text=paste0( 'names(NewPartials$', Gene, ')'  ))) ){
    Temp <- eval(parse(text=paste0( 'NewPartials$', Gene, '$', Tissue )))
    Rs <- Temp[,'SeedGene']
    row.names(Temp) <- Temp[, 'SeedGene']
    Temp <- as.data.frame( Temp[ ,(colnames(Temp) %in% 'SeedGene') == F ] )
    Temp[] <- lapply(Temp, function(x) as.numeric(as.character(x)))
     #Selct <- Temp[ RName, Temp[ RName, ]>0 ]
    if( dim(Temp)[2] > 1 ){
      
    }else{
      Cs<-row.names(Temp)
      Temp <- data.table::transpose(Temp)
      row.names(Temp) <- Rs
      colnames(Temp) <- Cs
    }
    for( RName in row.names(Temp) ){
     
      Selct <- Temp[ RName, Temp[ RName, ]>0 ]

      Vals <- as.vector( as.numeric(as.character( Selct[ 1 , Selct[1,] < 1 ] ) ))
      Vals <- c( Vals, -1*Vals )
      M <- mean( Vals )
      S <- sd( Vals )
      #Lim <- M + as.numeric( LIN[ Gene,]$LIN )*S
      FIND <- Y[ ,c(Gene,"StDevs")][ Y[ ,c(Gene,"StDevs")][,1] > 200, ]
      SDs <- FIND[ dim(FIND)[1], 2]
      if( Gene %in% c( "TREM2")){
        SDs <- 0.7
      }else{
        if( Gene %in% c( 'APOC1')){
          SDs <- 1.7
        }else{
          SDs <- 1.3
        }
      }
      Lim <- M + SDs*S
      Adds <- colnames( Selct[ , Selct > Lim ] )
      eval(parse(text=paste0( 'GSE_Target$', Gene, ' <- c(GSE_Target$', Gene, ', Adds)'  )))
    }
  }
}

# Cell Type enrichment by binomial test:
Actuals_Pval <- as.data.frame( matrix( 0, length( names(GSE_Target) ), length( names(CellTypeGenes) )) )
colnames(Actuals_Pval) <- names(CellTypeGenes) 
row.names(Actuals_Pval) <- names(GSE_Target)
Actuals_OR <- Actuals_Pval

for( G in names(GSE_Target)){
  eval(parse(text=paste0( 'N <- length( GSE_Target$', G, ')')))
  eval(parse(text=paste0( 'Genes <- GSE_Target$', G )))
  Genes <- Genes[ (Genes %in% Total_Genes) == T ]
  #Calc Actual Overlap
  for( CT in colnames(Actuals_Pval) ){
    #eval(parse(text=paste0( 'Actuals[ \'', G,'\',\'', CT,'\'] <- as.numeric( table( Genes %in% CellTypeGenes$', CT, ')[\'TRUE\'])')))
    eval(parse(text=paste0( 'Perc <- length(CellTypeGenes$', CT, ')/length( Total_Genes )')))
    eval(parse(text=paste0( 'Emp_Perc <- as.numeric( table( Genes %in% CellTypeGenes$', CT, ')[\'TRUE\'])/length( Genes )')))
    
    if( length( eval(parse(text=paste0('table(Genes %in% CellTypeGenes$', CT, ')' ))) ) > 1 ){ 
      eval(parse(text=paste0( 'N <- as.numeric( table( Genes %in% CellTypeGenes$', CT, ')[\'TRUE\'])' )))
      eval(parse(text=paste0( 'SIZE <- length( CellTypeGenes$', CT, ')' )))
      
      Foo <- binom.test( x=N, n=SIZE, p=Perc, alternative = c("two.sided") )
      #Poo <- prop.test(x=N, n=SIZE, p=Perc, alternative = "two.sided", correct = TRUE)
      
      if( Emp_Perc > Perc ){
        OR <- Emp_Perc/Perc
      }else{
        OR <- -1*( Perc/Emp_Perc )
      }
      #Foo$p.value
      
      eval(parse(text=paste0( 'Actuals_Pval[ \'', G,'\',\'', CT,'\'] <- Foo$p.value')))
      eval(parse(text=paste0( 'Actuals_OR[ \'', G,'\',\'', CT,'\'] <- OR')))
    }else{
      Emp_Perc <- 0
      eval(parse(text=paste0( 'N <- 0' )))
      eval(parse(text=paste0( 'SIZE <- length( CellTypeGenes$', CT, ')' )))
      
      Foo <- binom.test( N, SIZE, Perc )
      if( Emp_Perc == 0){
        OR <- NA
      }else{
        if( Emp_Perc > Perc ){
          OR <- Emp_Perc/Perc
        }else{
          OR <- -1*( Perc/Emp_Perc )
        }
      }
      eval(parse(text=paste0( 'Actuals_Pval[ \'', G,'\',\'', CT,'\'] <- Foo$p.value')))
      eval(parse(text=paste0( 'Actuals_OR[ \'', G,'\',\'', CT,'\'] <- OR')))
    }
  }
  Leng <- dim( Actuals_Pval )[2]
  eval(parse(text=paste0( 'Actuals_Pval[ \'', G, '\', ] <- p.adjust(Actuals_Pval[ \'', G, '\', ], method = \'fdr\', n = ', Leng,' )' )))
}

test_labels <- Actuals_Pval
test_labels[ test_labels< 0.05] <- "*"
test_labels[ test_labels > 0.05] <- ""


lin <- LIN
lin$LIN <- c( 0.7, 1.3,1.3,1.3,1.3,1.7,1.3,1.3 )
Mathys_G <- ggplot( data=PLOT_y, aes( x=StDevs, y=value, col=`Seed Gene`)) + 
  geom_point() + 
  geom_line() +
  geom_vline(data = lin, aes(xintercept = LIN, col=`Seed Gene`),linetype='dashed' ) +
  ylab("Partially Correlated Genes Included") +
  xlab("Standard Deviation Cutoff")

Mathys_G


setEPS()
postscript( 'STDEV_Cutoff.eps' )
  Mathys_G
dev.off()

#Actuals_OR <- Actuals_OR[colSums(!is.na(Actuals_OR)) > 1]
Actuals_OR[is.na(Actuals_OR)] <- 0
test_labels <- test_labels[ , colnames(Actuals_OR)]


makeColorRampPalette <- function(colors, cutoff.fraction, num.colors.in.palette)
{
  stopifnot(length(colors) == 4)
  ramp1 <- colorRampPalette(colors[1:2])(num.colors.in.palette * cutoff.fraction)
  ramp2 <- colorRampPalette(colors[3:4])(num.colors.in.palette * (1 - cutoff.fraction))
  return(c(ramp1, ramp2))
}

library(RColorBrewer)
library(grDevices)
cols <- colorRampPalette(c("navyblue", "deepskyblue4", "darkslategray2", "white", "darkgoldenrod2", "red"))(100)


Mathys_HeatMap <- pheatmap::pheatmap( as.matrix(Actuals_OR), col=cols, cluster_cols=F, display_numbers = test_labels, fontsize_number=40)
save_pheatmap_pdf(Mathys_HeatMap, "Mathys_HeatMap.pdf")


parentId = 'syn18936948';
activityName = 'Gene Set Enrichment';
activityDescription = 'Figure 4: gene set enrichment of genes implicated in TWAS regions';
thisFileName <- 'GeneSet_Expansion.Rmd'
# Github link
thisRepo <- githubr::getRepo(repository = "jgockley62/TWAS", ref="branch", refName='master')
thisFile <- githubr::getPermlink(repository = thisRepo, repositoryPath=paste0('code/',thisFileName))

CODE <- syn_temp$store(synapseclient$Folder(name = "Gene Set Enrichment Plots", parentId = parentId))

ENRICH_OBJ <-  syn_temp$store( synapseclient$File( path='STDEV_Cutoff.eps', name = 'StDev Cutoff values of Partial Correlations', parentId=CODE$properties$id ), activityName = activityName, executed = thisFile, activityDescription = activityDescription)
  
ENRICH_OBJ <-  syn_temp$store( synapseclient$File( path='Lake_HeatMap.pdf', name = 'Lake et.al CellType Specificity', parentId=CODE$properties$id ), activityName = activityName, executed = thisFile, activityDescription = activityDescription)

ENRICH_OBJ <-  syn_temp$store( synapseclient$File( path='Mathys_HeatMap.pdf', name = 'Mathys et.al CellType Specificity', parentId=CODE$properties$id ), activityName = activityName, executed = thisFile, activityDescription = activityDescription)
 


```
Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
